---
title: "Evaluation"
author: 
  - Erik Matovič
date: November 2021
output: 
  html_notebook:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
---

# Evaluation

## Read data and import libraries

```{r}
# for rendering run this command in console:
# rmarkdown::render("evaluation.Rmd", "html_notebook")
library(tidyverse)  
library(ggplot2)
data <- read_csv("time_tests.csv")
```

## Evaluation

```{r}
numProcesses <- data %>%
  select(processes) %>%
  distinct()

# size = nrows * ncols
numProcessesSize <- dim(numProcesses)[1] * dim(numProcesses)[2]

# set index
numProcessesIndex <- as.integer(1)

# display
numProcesses
numProcessesSize
```


```{r}
p1 = data %>%
  filter(processes == 1) %>% #as.integer(numProcesses[numProcessesIndex,])) %>%
  select(threads, time)
p1

# increment index
numProcessesIndex <- numProcessesIndex + 1

ggplot(p1, aes(x=time, y=factor(threads), group=1)) + geom_line(color="red") + 
  geom_point() + ggtitle("1 process")
```

```{r}
p2 = data %>%
  filter(processes == 2) %>%
  select(threads, time)
p2

# increment index
numProcessesIndex <- numProcessesIndex + 1

ggplot(p2, aes(x=time, y=factor(threads), group=1)) + geom_line(color="red") + 
  geom_point() + ggtitle("2 processes")
```

```{r}
p3 = data %>%
  filter(processes == 3) %>%
  select(threads, time)
p3

# increment index
numProcessesIndex <- numProcessesIndex + 1

ggplot(p3, aes(x=time, y=factor(threads), group=1)) + geom_line(color="red") + 
  geom_point() + ggtitle("3 processes")
```

```{r}
p4 = data %>%
  filter(processes == 4) %>%
  select(threads, time)
p4

# increment index
numProcessesIndex <- numProcessesIndex + 1

ggplot(p4, aes(x=time, y=factor(threads), group=1)) + geom_line(color="red") + 
  geom_point() + ggtitle("4 processes")
```

```{r}
p8 = data %>%
  filter(processes == 8) %>%
  select(threads, time)
p8

# increment index
numProcessesIndex <- numProcessesIndex + 1

ggplot(p8, aes(x=time, y=factor(threads), group=1)) + geom_line(color="red") + 
  geom_point() + ggtitle("8 processes")
```


```{r}
p16 = data %>%
  filter(processes == 16) %>%
  select(threads, time)
p16

# increment index
numProcessesIndex <- numProcessesIndex + 1

ggplot(p16, aes(x=time, y=factor(threads), group=1)) + geom_line(color="red") + 
  geom_point() + ggtitle("16 processes")
```

```{r}
data_label= data %>%
  mutate(labels = sub("^","P", sprintf("%sT%s",processes, threads)))
data_label
```

```{r}
ggplot(data_label, aes(x=factor(processes), y=factor(threads), label=labels)) + 
  geom_point(aes(size=time, color=time)) + 
  geom_text(nudge_y = 0.30)
```
Max:

```{r}
data_label[which.max(data_label$time),]
```

Min:

```{r}
data_label[which.min(data_label$time),]
```

